Fix staking modals
mgguild/gamevault-frontend pull request #19
Opened 2022-01-27 17:39 UTC by kojiadrianojr

Disable Claim action
![image](https://user-images.githubusercontent.com/43143132/151413347-4d96bf24-0f1f-4396-99b7-bf8bf67601b6.png)

Fix modals 
![Farms modals](https://user-images.githubusercontent.com/43143132/151413521-fcf47f33-3041-4c9c-aee2-8b7cc16993b3.gif)

2022-02-07 14:42 UTC, medardm requested changes
pa dynamic pls ng earned value

2022-02-07 14:42 UTC, medardm commented on src/views/Pools/components/ClaimAction/index.tsx
> +          <Earned>0</Earned>
nata naka static

2022-02-08 06:31 UTC, swengr-janan approved these changes
Dynamite!

2022-02-08 13:16 UTC, medardm requested changes

2022-02-08 13:16 UTC, medardm commented on src/views/Pools/components/ClaimAction/index.tsx
> +    const { onReward } = useClaim(stakingContract)
Do not reuse functions from LP staking that is not compatible in Pool-based

2022-02-09 20:18 UTC, medardm approved these changes
LGTM

2022-02-09 20:18 UTC, merged