Integrate fixed apr staking contract
mgguild/gamevault-frontend pull request #296
Opened 2022-07-07 13:42 UTC by medardm

closes #274  #268

2022-07-07 22:41 UTC, EAdornado approved these changes

2022-07-11 02:11 UTC, EAdornado approved these changes
All goods!

2022-07-12 08:15 UTC, swengr-janan requested changes

2022-07-12 08:15 UTC, swengr-janan commented on src/state/pools/index.ts
> +    console.log('updateUserAllowance: ', allowances)
kuys pa remove console.log

2022-07-19 07:02 UTC, EAdornado approved these changes
All goods!

2022-07-19 16:47 UTC, kojiadrianojr approved these changes

2022-07-20 08:37 UTC, swengr-janan requested changes
Typo
<img width="628" alt="Screen Shot 2022-07-20 at 4 35 30 PM" src="https://user-images.githubusercontent.com/61826995/179937220-d6b8e1bb-e0d0-43e3-b2eb-194461c3182a.png">

2022-07-20 08:45 UTC, swengr-janan approved these changes
AGITH!

2022-07-20 17:03 UTC, EAdornado approved these changes
All Gooooods!

2022-07-21 01:30 UTC, merged