Fix self-claiming not working
mgguild/gamevault-frontend pull request #348
Opened 2022-09-15 15:13 UTC by medardm

2022-09-15 15:14 UTC, swengr-janan requested changes
pa remove console log kuys

2022-09-15 15:14 UTC, swengr-janan commented on src/components/Launchpad/Content.tsx
> +  console.log(guildpad)
remove

2022-09-19 11:10 UTC, EAdornado approved these changes

2022-09-20 03:07 UTC, swengr-janan approved these changes
AGITH!

2022-09-20 03:07 UTC, merged